# Generated by Django 6.1 on 2026-08-18 12:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('load', 'Load'), ('gen', 'Generation')], max_length=4)),
                ('hour', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('dayofweek', models.IntegerField()),
                ('lag_1', models.FloatField()),
                ('lag_24', models.FloatField()),
                ('prediction', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precipitation_mm', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('is_weekend', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]), size=10)),
                ('is_raining', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')]), size=10)),
                ('sin_day_of_year', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('cos_day_of_year', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('sin_month', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('cos_month', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('sin_wind_dir', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('cos_wind_dir', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('avg_temp_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('min_temp_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('max_temp_c', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('avg_sea_level_pres_hpa', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('avg_wind_speed_kmh', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10)),
                ('prediction', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
